name: ci
on: [push, pull_request]

jobs:
  test:
    name: 'Run tests and checks on node ${{ matrix.node-version }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20', '22']
    steps:
      - uses: actions/checkout@v4
      - uses: mcous/js/actions/setup@5f58238fd9ec0c0de22d803153af70239bfbdc9c
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm check

  build:
    name: 'Build artifact and publish to npm on tags'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mcous/js/actions/setup@5f58238fd9ec0c0de22d803153af70239bfbdc9c
        with:
          registry-url: https://registry.npmjs.org/
      - run: pnpm build
      - name: 'Publish to npm'
        if: startsWith(github.ref, 'refs/tags/v')
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
